# Generated by Django 4.2.6 on 2023-11-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_userprofile_user_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gexing',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='个性签名'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_info',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='个人简介'),
        ),
    ]
