# Generated by Django 4.2.6 on 2023-11-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_gexing_alter_userprofile_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='imgs/default.jpg', upload_to='images/%Y/%m', verbose_name='用户头像'),
        ),
    ]
