# Generated by Django 4.2.6 on 2023-11-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catgory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('desc', models.TextField(blank=True, default='', max_length=255, null=True, verbose_name='分类描述')),
                ('add_data', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
