# Generated by Django 4.2.6 on 2023-11-06 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tag_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.tag', verbose_name='文章详情'),
        ),
    ]
